language: rust
services:
  - docker

jobs:
  include:
    - stage: test
      rust: stable
      script:
        - cargo build
        - cargo build --features=stream
        - cargo test
        - cargo test --features=stream
    - stage: test
      rust: nightly 
      script:
        - cargo build
        - cargo build --features=stream
        - cargo test
        - cargo test --features=stream
    - stage: test
      script:
        - docker run -ti jbaublitz/rust-musl-ci /bin/bash -c "cd neli && \
          git checkout $TRAVIS_COMMIT && \
          rustup default stable-x86_64-unknown-linux-musl && \ 
          /root/.cargo/bin/cargo build && \
          /root/.cargo/bin/cargo build --features=stream && \
          /root/.cargo/bin/cargo test && \
          /root/.cargo/bin/cargo test --features=stream"
    - stage: test
      script:
        - docker run -ti jbaublitz/rust-musl-ci /bin/bash -c "cd neli && \
          git checkout $TRAVIS_COMMIT && \
          rustup default nightly-x86_64-unknown-linux-musl && \ 
          /root/.cargo/bin/cargo build && \
          /root/.cargo/bin/cargo build --features=stream && \
          /root/.cargo/bin/cargo test && \
          /root/.cargo/bin/cargo test --features=stream"

before_install:
  - docker build -t jbaublitz/rust-musl-ci ./test
