[package]
name = "neli"
version = "0.4.3-r1"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[lib]
name = "neli"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
libc = { git = "https://github.com/jbaublitz/libc", branch = "musl-netlink-support" }

[dependencies.tokio]
version = "0.1"
optional = true

[dependencies.mio]
version = "0.6"
optional = true

[dependencies.buffering]
version = "0.3.4"
features = ["copy"]

[features]
default = []
stream = ["tokio", "mio"]
